name:  Harry CDRelease CI Pipeline - Config Lib

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]    
  workflow_dispatch:

  
jobs:
  release-project:
      name: Release to Github Releases
      runs-on: windows-latest
     # needs: build
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Build project # This would actually build your project, using zip for an example artifact
          run:  pwd
        - name: list all  
          run:  ls -ah
        - name: compress archive
          run:  Compress-Archive -Path .\* -DestinationPath .\archive.zip
